add test1
julia951/playwright_tests_with_po pull request #1
Opened 2024-06-29 10:12 UTC by julia951

2024-06-29 12:02 UTC, hlazkov commented on src/tests/sortingCheck.spec.js
> +        let itemNames = await inventoryPage.getItemNames();
Please use const whereever its applicible

2024-06-29 12:03 UTC, hlazkov commented on src/tests/sortingCheck.spec.js
> +       await inventoryPage.sortItems('az');
Should we add other sorting options in this PR?

2024-06-29 12:04 UTC, hlazkov commented on src/tests/sortingCheck.spec.js
> +        let sortedItemNames = [...itemNames].sort();
What is the difference for [...itemNames].sort(); and itemNames.sort(); ?

2024-06-29 12:05 UTC, hlazkov commented on src/tests/sortingCheck.spec.js
> +       await inventoryPage.sortItems('za');
Lets split to separate tests, so they would be independed

2024-06-29 12:05 UTC, hlazkov requested changes
Please pay attention to comments provided

2024-06-30 13:21 UTC, hlazkov requested changes
Lets add 2 tests for sorting by price as well!

2024-07-01 12:47 UTC, EugenePetrik approved these changes
Good job!

2024-07-01 13:15 UTC, merged